### ISSUE TITLE
possible dependency conflict between tensorflow and layer-api

### ISSUE THREAD

**Issue by fcakyon** [layerai/sdk#135]
We are having a weird error in SAHI CI tests: https://github.com/obss/sahi/pull/501/checks

Should we upper bound layer or layer-api version in CI?
What is the latest layer-api version that supports tensorflow 2.9.1?

## possible reason
tensorflow 2.9.1 requires protobuf<3.20 https://github.com/tensorflow/tensorflow/pull/56200/files
layer-api  0.9.365520 requires protobuf>=3.20.0 https://github.com/obss/sahi/pull/501/checks#step:16:86

## Versions:
`layer 0.10.2517581172`
`layer-api  0.9.365520`
`mlflow 1.26.1`
`protobuf 3.19.4`
`tensorflow 2.9.1`
`tensorflow_hub 0.12.0`

## Error message:
```bash
AttributeError: Enum ModelFlavor has no value defined for name 'ValueType'
```

## Error trace:
```bash
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/unittest/mock.py", line 1249, in patched
    arg = exit_stack.enter_context(patching)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/contextlib.py", line 427, in enter_context
    result = _cm_type.__enter__(cm)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/unittest/mock.py", line 1291, in __enter__
    self.target = self.getter()
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/unittest/mock.py", line 1465, in <lambda>
    getter = lambda: _importer(target)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/unittest/mock.py", line 1161, in _importer
    thing = __import__(import_path)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/layer/__init__.py", line 4, in <module>
    from .contracts.models import Model  # noqa
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/layer/contracts/models.py", line 11, in <module>
    from layer.flavors.base import ModelFlavor, ModelRuntimeObjects
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/layer/flavors/__init__.py", line 1, in <module>
    from .base import ModelFlavor  # noqa
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/layer/flavors/base.py", line 19, in <module>
    class ModelFlavor(metaclass=ABCMeta):
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/layer/flavors/base.py", line 37, in ModelFlavor
    ) -> PBModelFlavor.ValueType:
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/google/protobuf/internal/enum_type_wrapper.py", line 115, in __getattr__
    self._enum_type.name, name))
AttributeError: Enum ModelFlavor has no value defined for name 'ValueType'
```

**Comment by volkangurel** [comment]
Thanks for the detailed report @fcakyon! I believe we'll need to make some code changes to support `tensorflow 2.9.1`, but we'll prioritize that right away and target tomorrow to ship a fix.

**Comment by eminn** [comment]
Hi @fcakyon, [this](https://github.com/layerai/sdk/commit/204f6945c558f50e42be740549cc7d744ce9fc0a) should fix the errors you are seeing with protobuf 3.19.4. For the `layer-api` we are thinking to lift the restriction after this fix.

**Comment by mecevit** [comment]
I'm opening a PR on SAHI repo. I will keep you posted

**Comment by fcakyon** [comment]
@eminn thanks for the update!

**Comment by fcakyon** [comment]
All tests are passing now 🚀 https://github.com/obss/sahi/actions/runs/2525202173
