### ISSUE TITLE
error when torch.tensor image logging

### ISSUE THREAD

**Issue by fcakyon** [layerai/sdk#290]
## steps

```python
import torch
import layer

# inside layer decorated training function:
image = torch.rand((480, 640, 3))
layer_image = layer.Image(image, format="HWC")
layer.log({'image': layer_image}, step=1)
```

## error

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../lib/python3.8/site-packages/layer/main.py", line 874, in log
    log_data_runner.log(data=data, epoch=step)
  File ".../lib/python3.8/site-packages/layer/logged_data/log_data_runner.py", line 96, in log
    self._log_image(tag=tag, img_value=value, epoch=epoch)
  File ".../lib/python3.8/site-packages/layer/logged_data/log_data_runner.py", line 127, in _log_image
    img = img_value.get_image()
  File ".../lib/python3.8/site-packages/layer/contracts/logged_data.py", line 78, in get_image
    return transforms.ToPILImage()(self.img)
  File ".../lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 227, in __call__
    return F.to_pil_image(pic, self.mode)
  File ".../lib/python3.8/site-packages/torchvision/transforms/functional.py", line 254, in to_pil_image
    raise ValueError(f"pic should not have > 4 channels. Got {pic.shape[-3]} channels.")
ValueError: pic should not have > 4 channels. Got 480 channels.
```

**Comment by mecevit** [comment]
@fcakyon This should fix that:

https://github.com/layerai/sdk/pull/293

**Comment by fcakyon** [comment]
Error is gone but the images are incorrectly logged
![incorrect_conf_matrix](https://user-images.githubusercontent.com/34196005/183762986-d3d78861-b6a5-4cc9-a100-3f0f5c6f4bab.png)

**Comment by fcakyon** [comment]
## bug

This line is incorrect:
https://github.com/layerai/sdk/blob/17859e40502a0188933a3ff2efffeebdc0d3f922/layer/contracts/logged_data.py#L80

## explenation

```python
import torch

# create 480x640x3 HWC image
image = torch.rand((480, 640, 3))

# this is not correct:
torch.transpose(image,2,0).shape
> torch.Size([3, 640, 480])

# this is correct:
image.permute(2,0,1).shape
> torch.Size([3, 480, 640])
```

## fix
```python
self.img = self.img.permute(2,0,1)
```

**Comment by mecevit** [comment]
Thanks @fcakyon. Fixed here and added image dimension tests:

https://github.com/layerai/sdk/pull/298
