### ISSUE TITLE
error when logging pillow image

### ISSUE THREAD

**Issue by fcakyon** [layerai/sdk#333]
## summary

Having below error when trying to log Pillow image. 
`layer==0.10.2878787422`
`layer-api==0.9.378400`

## minimal example

```python
import numpy as np
import sklearn.metrics
import io
import matplotlib.pyplot as plt
from PIL import Image
import layer

def log_image():
    conf_mat = np.array(((3, 2),(1, 4)))
    display = sklearn.metrics.ConfusionMatrixDisplay(confusion_matrix=conf_mat, display_labels=self.labels)
    display.plot()
    fig = display.figure_
    buf = io.BytesIO()

    fig.savefig(buf, format="png")
    buf.seek(0)
    image = Image.open(buf)
    plt.close(fig)

    layer.log({'image': image})

layer.login_with_api_key(layerai_api_token)
layer.init(layerai_project_name)

layer.model(layer_model_name)(log_image)()
```

## error trace

```bash
Traceback (most recent call last):
  File ".../lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File ".../lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File ".../lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='logged-data--layer2022040715233176650000001a.s3.eu-west-1.amazonaws.com', port=443): Max retries exceeded with url: /5961363b-761b-44fa-a302-8faf8486cda5/cc8369db-d866-4ada-bcbb-22e471b4736b/data/train/confusion_matrix?x-amz-acl=public-read&X-Amz-Security-Token=... (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f74304e0bb0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../lib/python3.8/site-packages/layer/exceptions/exception_handler.py", line 31, in wrapper
    return wrapped(*args, **kwargs)
  File ".../lib/python3.8/site-packages/layer/executables/entrypoint/model_trainer.py", line 173, in _train
    model = train_model_func(
  File ".../train.py", line 123, in _run_experiment
    trainer.fit(lit_module, data_module)
  File ".../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File ".../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File ".../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File ".../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File ".../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage
    return self._run_train()
  File ".../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1285, in _run_train
    self.fit_loop.run()
  File ".../lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 201, in run
    self.on_advance_end()
  File ".../lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 286, in on_advance_end
    epoch_end_outputs = self.trainer._call_lightning_module_hook("training_epoch_end", epoch_end_outputs)
  File ".../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1552, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File ".../tasks/base.py", line 292, in training_epoch_end
    self._log_image("train/confusion_matrix", image)
  File ".../tasks/base.py", line 264, in _log_image
    logger.experiment.log({log_name: image}, step=self.current_epoch)
  File ".../lib/python3.8/site-packages/layer/main/utils.py", line 9, in inner
    return func(*args, **kwargs)
  File ".../lib/python3.8/site-packages/layer/main/log.py", line 197, in log
    log_data_runner.log(data=data, epoch=step, category=category)
  File ".../lib/python3.8/site-packages/layer/logged_data/log_data_runner.py", line 110, in log
    self._log_image(
  File ".../lib/python3.8/site-packages/layer/logged_data/log_data_runner.py", line 175, in _log_image
    self._log_pil_image(tag=tag, image=img, epoch=epoch, category=category)
  File ".../lib/python3.8/site-packages/layer/logged_data/log_data_runner.py", line 353, in _log_pil_image
    resp = s.put(presigned_url, data=buffer.getvalue())
  File ".../lib/python3.8/site-packages/requests/sessions.py", line 589, in put
    return self.request('PUT', url, data=data, **kwargs)
  File ".../lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ".../lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File ".../lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='logged-data--layer2022040715233176650000001a.s3.eu-west-1.amazonaws.com', port=443): Max retries exceeded with url: /5961363b-761b-44fa-a302-8faf8486cda5/cc8369db-d866-4ada-bcbb-22e471b4736b/data/train/confusion_matrix?x-amz-acl=public-read&X-Amz-Security-Token=...
```

**Comment by dpp23** [comment]
@fcakyon thank you for reporting this.

I was unable to reproduce the issue with the snippet you provided - the image was logged correctly https://app.layer.ai/dimitar/repro-test/models/repro-test

Is this happening consistently for you or from time to time? Is there anything specific to your environment that might block uploads to AWS S3?

**Comment by fcakyon** [comment]
@dpp23 it is happening from time to time, I had 4 successful runs then the 5th time all process quits because of this error. It may be caused by my temporary connection issues. 

Can you update `layer` so that it skips logging or it caches logging material till the connection is restored so that the whole process is not stopped by just a temporary connection issue? 

In Neptune.ai and WANDB my process is not killed by short connection errors, they cache and upload the data when the connection is restored.

**Comment by dpp23** [comment]
@fcakyon thank you - this explains the route cause. We will look into ways to make this more stable.

**Comment by dpp23** [comment]
Hi @fcakyon as part of https://github.com/layerai/sdk/pull/335 we've just shipped a small improvement on this. We will revisit a more robust way to handle logging as part of our roadmap, but this should make things more stable in the meantime
