### ISSUE TITLE
Failed to get an access token

### ISSUE THREAD

**Issue by kadirnar** [layerai/sdk#97]
Hi,

I want to use layer library in Yolov5 model. When I run this command it gives an error.
```
my_model = layer.get_model("layer/instance-segmentation/models/object_detector").get_train()
```
Error Message:
```
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://auth.app.layer.ai/oauth/token')
The above exception was the direct cause of the following exception
```
```
File "/home/kadir/miniconda3/envs/layer/lib/python3.7/site-packages/layer/auth.py", line 277, in refresh
    raise AuthException("failed to get an access token.") from exc
layer.exceptions.exceptions.AuthException: failed to get an access token.
```
Env:
- Pop Os(22.04) 
- VsCode(Conda)

**Comment by mwitiderrick** [comment]
Hello @kadirnar did you try `layer.logout()` then `layer.login()`?

**Comment by kadirnar** [comment]
I am following the steps in Yolov5 notebook. [Yolov5-Layer](https://colab.research.google.com/github/layerai/examples/blob/main/yolov5-object-detection/notebooks/demo.ipynb) 
Editing it this way fixed the error.
```
layer.logout()
layer.login()
my_model = layer.get_model("layer/instance-segmentation/models/object_detector").get_train()
```
What do I need to do to use the custom yolov5 model in the layer library?

**Comment by kadirnar** [comment]
Hi @yuranos,

Yes, I solved the problem. I recommend editing this tutorial. [Layer-Examples](https://github.com/layerai/examples/tree/main/yolov5-object-detection)

How can I use custom yolov5 model?

**Comment by govu** [comment]
Hi @kadirnar,

Was it something specific to torch and torchvision version compatibility? Can you tell us how you fixed the problem so that we can update the tutorial?

**Comment by kadirnar** [comment]
Hi @govu ,

I solved the problem by logging in with token.(for ubuntu)
```
layer.logout()
layer.login()
```
When I try on Windows, I get the same error again.
```
Traceback (most recent call last):
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\site-packages\layer\auth.py", line 275, in refresh
    resp.raise_for_status()
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://auth.app.layer.ai/oauth/token')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\kadir\Desktop\kadir\layer\yolov5_layer.py", line 3, in <module>
    my_model = layer.get_model("layer/instance-segmentation/models/object_detector").get_train()
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\site-packages\layer\main.py", line 311, in get_model
    config = asyncio_run_in_thread(ConfigManager().refresh(allow_guest=True))
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\site-packages\layer\utils\async_utils.py", line 13, in asyncio_run_in_thread
    raise future.exception()  # type: ignore
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\site-packages\layer\utils\async_utils.py", line 8, in _run
    return asyncio.run(coro)
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\site-packages\layer\config\config_manager.py", line 66, in refresh
    creds = await creds_client.refresh(config.credentials)
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\site-packages\layer\auth.py", line 277, in refresh
    raise AuthException("failed to get an access token.") from exc
layer.exceptions.exceptions.AuthException: failed to get an access token.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000222FAF4D040>
Traceback (most recent call last):
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```
When I log in with the token, I get the following error:
```
Traceback (most recent call last):
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\site-packages\layer\clients\model_catalog.py", line 199, in load_model_runtime_objects
    S3Util.download_dir(
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\site-packages\layer\utils\s3.py", line 42, in download_dir
    for obj in bucket.objects.filter(Prefix=s3_path.key):
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\site-packages\boto3\resources\collection.py", line 81, in __iter__
    for page in self.pages():
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\site-packages\boto3\resources\collection.py", line 171, in pages
    for page in pages:
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\site-packages\botocore\paginate.py", line 253, in __iter__
    response = self._make_request(current_kwargs)
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\site-packages\botocore\paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\site-packages\botocore\client.py", line 415, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\site-packages\botocore\client.py", line 745, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (RequestTimeTooSkewed) when calling the ListObjects operation: The difference between the request time and the current time is too large.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\kadir\Desktop\kadir\layer\yolov5_layer.py", line 4, in <module>
    my_model = layer.get_model("layer/instance-segmentation/models/object_detector").get_train()
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\site-packages\layer\main.py", line 338, in get_model
    model = _ui_progress_with_tracker(
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\site-packages\layer\main.py", line 416, in _ui_progress_with_tracker
    result = callback()
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\site-packages\layer\main.py", line 325, in callback
    return _load_model_runtime_objects(client, model, state, no_cache)
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\site-packages\layer\main.py", line 370, in _load_model_runtime_objects
    model_runtime_objects = client.model_catalog.load_model_runtime_objects(
  File "C:\Users\kadir\AppData\Local\Programs\Python\Python39\lib\site-packages\layer\clients\model_catalog.py", line 215, in load_model_runtime_objects
    raise LayerClientException(f"Error while loading model, {ex}")
layer.exceptions.exceptions.LayerClientException: Error while loading model, An error occurred (RequestTimeTooSkewed) when calling the ListObjects operation: The difference between the request time and the current time is too large.
```

**Comment by volkangurel** [comment]
@kadirnar we don't currently support Windows, can you please try using Layer with the Windows Subsystem for Linux?

**Comment by fcakyon** [comment]
@volkangurel do you have any plans to support Windows?

**Comment by mecevit** [comment]
Yes, it's in the roadmap which we will open source soon.
